"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.28.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import dj_database_url # 引入這個套件
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-+rjlt85lfu6n4u1l7)xsc+5rj3yony6j_*x$va+nosl#(x=9xp"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'stock_app', # <--- 加入我們剛建立的 App
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Render 部署需要這行
    'django.contrib.sessions.middleware.SessionMiddleware',  # [必要] 修正 admin.E408
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware', # [必要] 修正 admin.E408
    'django.contrib.messages.middleware.MessageMiddleware',    # [必要] 修正 admin.E409
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request', # [必要] 修正 admin.W411
                'django.contrib.auth.context_processors.auth', # [必要] 修正 admin.E402
                'django.contrib.messages.context_processors.messages', # [必要] 修正 admin.E404
            ],
        },
    },
]
WSGI_APPLICATION = "config.wsgi.application"

import os
import dj_database_url # 引入這個套件

# ... (前面的程式碼)

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'stock_app', # <--- 加入我們剛建立的 App
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # <--- 加入這行，用於在 Render 處理靜態檔案
    'django.contrib.sessions.middleware.SessionMiddleware',
    # ... (其他 middleware)
]

# 設定 Templates 路徑 (讓 Django 找得到我們的 HTML)
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], # <--- 加上這行
        'APP_DIRS': True,
        # ...
    },
]

# 資料庫設定 (關鍵！)
# 本地開發用 SQLite，線上如果有環境變數 DATABASE_URL 則用 Aiven
DATABASES = {
    'default': dj_database_url.config(
        default='sqlite:///' + os.path.join(BASE_DIR, 'db.sqlite3'),
        conn_max_age=600
    )
}

# 靜態檔案設定 (Render 部署需要)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# 安全性設定 (部署時自動讀取環境變數)
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-local-key')
DEBUG = 'RENDER' not in os.environ # 如果在 Render 上，Debug 會自動變 False
ALLOWED_HOSTS = ['*'] # 允許所有網域連線